[target.aarch64-apple-darwin]
# Should pickup best Apple silicon target automatically
rustflags = ["-C", "target-cpu=native"]

[target.armv7-unknown-linux-musleabihf]
# Cortex-A53 (RPi3's CPU) optimizations
rustflags = [
    "-C", "target-cpu=cortex-a53",
    "-C", "target-feature=+neon,+vfp4",
]
